title: Blog de Lenguaje
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Temas Propuesto
    url: /about
  - title: Autores
    url: /contact

social:
  github: BlogdeLenguaje
  twitter: LuisWorkout98
  facebook: profile.php?id=100010939398193
  email: tuttorial5612@gmail.com
google_analytics: "UA-58263416-1"
